name: nextjs-github-actions

on:
  push:
    branches:
      - main
    paths-ignore:
      - README.md
  pull_request:
    branches:
      - main

env:
  GMAIL_USER: ${{ secrets.GMAIL_USER }}
  GMAIL_PASS: ${{ secrets.GMAIL_PASS }}
  METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  ORG_ID: ${{ secrets.ORG_ID }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

jobs:
  setup_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

  linter_job:
    needs: setup_job
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: npm run lint

  cypress_job:
    needs: [setup_job, linter_job]
    runs-on: ubuntu-latest
    steps:
      - name: Start Next.js server
        run: npm run dev &
        env:
          PORT: 3000

      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          spec: cypress/integration/1-my-tests/**/*.spec.js
        continue-on-error: true

      - name: Upload Cypress artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: cypress-results
          path: cypress/results/*

  metrics_job:
    needs: cypress_job
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub metrics
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_languages_limit: 4

      - name: Update README with metrics
        run: |
          awk '/## Resultados de Métricas/ {print; print "![Metrics](github-metrics.svg)"; next} 1' README.md > temp.md && mv temp.md README.md
          git config --global user.email "your-email@gmail.com"
          git config --global user.name "your-github-username"
          git add README.md
          git commit -m "Update README.md with GitHub metrics" || true
          git push origin main

  deploy_job:
    needs: metrics_job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: "--prod"

  notification_job:
    needs: [linter_job, cypress_job, deploy_job, metrics_job]
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          JOB_RESULTS="Resultados del flujo de trabajo:\n"
          JOB_RESULTS+=" - Linter: ${{ needs.linter_job.result }}\n"
          JOB_RESULTS+=" - Cypress: ${{ needs.cypress_job.result }}\n"
          JOB_RESULTS+=" - Deployment: ${{ needs.deploy_job.result }}\n"
          JOB_RESULTS+=" - Metrics: ${{ needs.metrics_job.result }}\n"
          curl -s -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="$(echo -e "$JOB_RESULTS")"
